name: deeppeak
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<1.25.0
  - scikit-learn
  - tqdm
  - shap
  - ipykernel
  - pybedtools # bed to df
  - pyyaml
  - pip
  - pip:
    - tensorflow[and-cuda]==2.14.0
    - weblogo
    - pyBigWig # bigwig file indexing
    - pyfaidx # bed file indexing
    - fasta # pyfaidx
    - flake8 # code linting
    - wandb==0.15.12
    - matplotlib
    - pandas==2.1.3
    - chardet # wandb issue
    - fastism
    - tabulate
    - seaborn==0.12.2
    - modisco-lite
    - vizsequence
