name: deeppeak
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<1.25.0
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - shap
  - ipykernel
  - pybedtools
  - pip
  - pip:
    - tensorflow[and-cuda]==2.8.0
    - protobuf==3.20.0 # tensorflow issue
    - weblogo
    - pyBigWig # for bigwig file indexing
    - pyfaidx # bed file indexing
    - fasta # for pyfaidx
