# !!! DON'T EDIT THIS FILE !!! 
# Default configuration file for the project.
# Instead, create a user.yml file in /configs and
# copy the contents of this file into the user.yml file.
# Add/overwrite the values in the user.yml file.

# general
project_name: 'mouse'  # used for naming output folders
num_classes: 19
seq_len: 2114
target_len: 1000

# Train/val/test
val: ['chr8', 'chr10']
test: ['chr9', 'chr18']

# Training
wandb: True
epochs: 40
batch_size: 128
learning_rate: 0.001
patience: 5  # number of epochs to wait before early stopping
pretrained_model_path: ''  # continue from .keras checkpoint. Leave empty if starting from scratch
shuffle: True
mixed_precision: True  # use mixed precision training (recent GPUs only)

# Debugging
fraction_of_data: 1.0  # fraction of data to use for training. Only lower for debugging.
profile: False  # profile training with TensorBoard profiler
seed: 0  # set seed for reproducibility. Set to 0 for random seed

# augmentations (online)
augment_complement: True  # inverse complement base pairs during training (50 % chance)

# Model architecture
## First convblock
first_conv_filters: 512
first_conv_filter_size: 5
first_conv_pool_size: 0
first_conv_activation: 'gelu'
first_conv_l2: 0.00001
first_conv_dropout: 0.1
first_conv_res: False

## Chrombp Conv blocks after first conv layer
num_filters: 512
n_dil_layers: 3
filter_size: 3
activation: 'relu'  # 'activation_name' or 'none'
l2: 0.00001
dropout: 0.1  # set to 0.0 for no dropout
batch_norm: True
dense_bias: True
