# Default configuration file for the project.
# !!! Don't edit this file directly !!! 
# Instead, create a user.yml file in /configs and
# add/overwrite the values in the user.yml file.
# User configs take priority over default configs.
# Only update default configs after extensive testing and discussion with team.

# general
project_name: 'mouse'  # used for naming output folders
num_classes: 19
seq_len: 2114

# Train/val/test
val: ['chr8', 'chr10']
test: ['chr9', 'chr18']
shuffle_buffer_size: 10000

# Training
wandb: True
epochs: 60
batch_size: 256
learning_rate: 0.001
fraction_of_data: 1.0  # fraction of data to use for training. Only lower for debugging.
patience: 5  # number of epochs to wait before early stopping
path_to_pretrained_model: ''  # continue from checkpoint. Leave empty if starting from scratch

# augmentations
augment_complement: True  # complement base pairs

# Model architecture
## First convblock
first_conv_filters: 512
first_conv_filter_size: 5
first_conv_pool_size: 0
first_conv_activation: 'gelu'
first_conv_l2: 0.00001
first_conv_dropout: 0.1
first_conv_res: False

## Chrombp Conv blocks after first conv layer
num_filters: 512
n_dil_layers: 8
filter_size: 3
activation: 'relu'
l2: 0.00001
dropout: 0.1
dense_bias: True
