name: Check Sphinx Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    name: Build Sphinx Documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install ".[doc]"

      - name: Build Documentation and Check for Warnings
        working-directory: docs
        run: |
          make clean
          make html | tee sphinx-output.log
          if grep -q "WARNING:" sphinx-output.log; then
            echo "Sphinx build generated warnings!"
            exit 1
          fi
          if grep -q "ERROR:" sphinx-output.log; then
            echo "Sphinx build generated errors!"
            exit 1
          fi
          if grep -q "Exception occurred:" sphinx-output.log; then
            echo "Sphinx build failed!"
            exit 1
          fi
      - name: Upload Documentation Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-output-log
          path: docs/sphinx-output.log
